N =input('Write Something: ')
print('Informations')
print('Numeric: ', N.isnumeric())
print('Alphabetic: ', N.isalpha())
print('Alphabetic Numeric: ', N.isalnum())
print('Lower: ', N.islower())
print('Supper: ', N.isupper())
