print('=====Gerador de Tabuada=====')
A = int(input('Digite Um Número: '))
print(f'{A}x1= {A*1}')
print(f'{A}x2= {A*2}')
print(f'{A}x3= {A*3}')
print(f'{A}x4= {A*4}')
print(f'{A}x5= {A*5}')
print(f'{A}x6= {A*6}')
print(f'{A}x7= {A*7}')
print(f'{A}x8= {A*8}')
print(f'{A}x9= {A*9}')
print(f'{A}x10= {A*10}')